export const products = [
  {
    id: 1,
    title: 'Expresso Tradicional',
    img: '/assets/images/tradicional.svg',
    tags: ['tradicional'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 5.9,
  },
  {
    id: 2,
    title: 'Expresso Americano',
    img: '/assets/images/americano.svg',
    tags: ['tradicional'],
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 5.9,
  },
  {
    id: 3,
    title: 'Expresso Cremoso',
    img: '/assets/images/cremoso.svg',
    tags: ['tradicional'],
    description: 'Café expresso tradicional com espuma cremosa',
    price: 5.9,
  },
  {
    id: 4,
    title: 'Expresso Gelado',
    img: '/assets/images/gelado.svg',
    tags: ['tradicional', 'gelado'],
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 6.9,
  },
  {
    id: 5,
    title: 'Café com Leite',
    img: '/assets/images/cafe-com-leite.svg',
    tags: ['tradicional', 'com leite'],
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 6.9,
  },
  {
    id: 7,
    title: 'Latte',
    img: '/assets/images/latte.svg',
    tags: ['tradicional', 'com leite'],
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 6.9,
  },
  {
    id: 8,
    title: 'Capuccino',
    img: '/assets/images/capuccino.svg',
    tags: ['tradicional', 'com leite'],
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 6.9,
  },
  {
    id: 9,
    title: 'Macchiato',
    img: '/assets/images/macchiato.svg',
    tags: ['tradicional', 'com leite'],
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 6.9,
  },
  {
    id: 10,
    title: 'Mocaccino',
    img: '/assets/images/mocaccino.svg',
    tags: ['tradicional', 'com leite'],
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 6.9,
  },
  {
    id: 11,
    title: 'Chocolate Quente',
    img: '/assets/images/chocolate-quente.svg',
    tags: ['tradicional', 'com leite'],
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 6.9,
  },
]
