export const products = [
  {
    id: 1,
    title: 'Expresso Tradicional',
    img: '',
    tags: ['tradicional'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 5.9,
  },
  {
    id: 2,
    title: 'Expresso Americano',
    img: '',
    tags: ['tradicional'],
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 5.9,
  },
  {
    id: 3,
    title: 'Expresso Cremoso',
    img: '',
    tags: ['tradicional'],
    description: 'Café expresso tradicional com espuma cremosa',
    price: 5.9,
  },
  {
    id: 4,
    title: 'Expresso Gelado',
    img: '',
    tags: ['tradicional', 'gelado'],
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 6.9,
  },
  {
    id: 5,
    title: 'Café com Leite',
    img: '',
    tags: ['tradicional', 'com leite'],
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 6.9,
  },
  {
    id: 6,
    title: 'Café com Leite',
    img: '',
    tags: ['tradicional', 'com leite'],
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 6.9,
  },
  {
    id: 7,
    title: 'Latte',
    img: '',
    tags: ['tradicional', 'com leite'],
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 6.9,
  },
  {
    id: 8,
    title: 'Capuccino',
    img: '',
    tags: ['tradicional', 'com leite'],
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 6.9,
  },
  {
    id: 9,
    title: 'Macchiato',
    img: '',
    tags: ['tradicional', 'com leite'],
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 6.9,
  },
  {
    id: 10,
    title: 'Mocaccino',
    img: '',
    tags: ['tradicional', 'com leite'],
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 6.9,
  },
  {
    id: 11,
    title: 'Chocolate Quente',
    img: '',
    tags: ['tradicional', 'com leite'],
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 6.9,
  },
  {
    id: 12,
    title: 'Cubano',
    img: '',
    tags: ['especial', 'alcoólico', 'gelado'],
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 8.9,
  },
  {
    id: 13,
    title: 'Havaiano',
    img: '',
    tags: ['especial'],
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 8.9,
  },
  {
    id: 14,
    title: 'Árabe',
    img: '',
    tags: ['especial'],
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 10.9,
  },
  {
    id: 15,
    title: 'Irlandês',
    img: '',
    tags: ['especial', 'alcoólico'],
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 10.9,
  },
]
